apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  kafka:
    config:
       socket.send.buffer.bytes: 10240000
       socket.receive.buffer.bytes: 10240000
       socket.request.max.bytes: 100000012
       auto.create.topics.enable: true
       offsets.topic.replication.factor: 2
       transaction.state.log.min.isr: 1
       transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    resources: {}
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
    version: 2.4.1
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    replicas: 1
    resources: {}
    storage:
      deleteClaim: true
      size: 8Gi
      type: persistent-claim
  entityOperator:
    topicOperator: {}
    userOperator: {}
