apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prod-zookeeper
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prod-kafka
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: kafka
