apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster-zookeeper-0
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster-kafka-0
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-claim
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: mysql
